### ISSUE TITLE
Optional LED diagram still missing

### ISSUE THREAD

**Issue by kiwisaurio** [Dwin17/bento#5]
Hi,

I've ordered a few PCBs and I want to create a bento with LED retroilumination on the keys. As your guide tells on imgur.com, there will be a future guide, but still nothing. I just want to know where I have to place the resistors and the mosfet to keep going with my project.

Thank you btw.

**Comment by Dwin17** [comment]
Hi there. Unfortunately due to change life circumstances, I no longer have the time to make updates to this project. However to answer your question, I would recommend opening up the PCB files on a program like KiCAD to locate the appropriate locations for each resistor/mosfet. Note that there are two types of resistors that you'll need and their placement matters. Orientation of the resistors do not matter.
